Reland "Don't ignore exit_code when collecting swarming tests & merging results"
This reverts commit 9736706ddbac7bf5f076b67db4ef8c00a4721356.

Reason for revert: Gate the new behavior around an experiment

Unless the per-builder experiment is enabled, this change is a safe
no-op. Will roll out the experiment over time then eventually
enable it unconditionally when it's safe to do so.

Original change's description:
> Revert "Don't ignore exit_code when collecting swarming tests & merging results"
>
> This reverts commit 9925bf8c1053c77b90569663e7dbfa6999e9bdab.
>
> Reason for revert: potential failures on android bots:
> https://ci.chromium.org/ui/p/chromium/builders/try/android-marshmallow-x86-rel/590822/overview
>
> TypeError: a bytes-like object is required, not 'str'
>
> Original change's description:
> > Don't ignore exit_code when collecting swarming tests & merging results
> >
> > For ages the chromium recipe has silently ignored failures in
> > merge/collect scripts. This can lead to issue where a merge script
> > breaks and there's no signal that's surfaced in the build.
> >
> > See:
> > https://ci.chromium.org/ui/p/chromium/builders/try/linux-rel/1109563/overview
> > That build has no indication that it's failing every invocation
> > of merge_scripts/code_coverage/merge_results.py.
> >
> > But after this, any failure in merge scripts will cause the build to
> > fail. eg: See how that same build fails:
> > https://ci.chromium.org/swarming/task/5ce479058c452510?server=chromium-swarm.appspot.com
> >
> > Note that it fails the build early. Any failure in a merge script
> > will immediately fail the build rather than delaying the failure and
> > letting all current pending tests finish. This shouldn't be too big
> > of an issue because merge script failures should hopefully be pretty rare, and adding the plumbing in the recipe to delay their failure
> > would likely be more trouble than it's worth.
> >
> > Additional LED builds:
> >
> > A m104 linux-rel run:
> > https://ci.chromium.org/swarming/task/5ce105abfbc0b510?server=chromium-swarm.appspot.com
> >
> > A trunk win10 run:
> > https://ci.chromium.org/swarming/task/5ce11128e8ae1e10?server=chromium-swarm.appspot.com
> >
> > A trunk mac-rel run:
> > https://ci.chromium.org/swarming/task/5ce111dbdd908010?server=chromium-swarm.appspot.com
> >
> > A build with expired tasks that continues on as normal:
> > https://ci.chromium.org/swarming/task/5ccaf2a435692310?server=chromium-swarm.appspot.com
> >
> > A m96 linux-chromeos-rel run:
> > https://ci.chromium.org/swarming/task/5ce440ee5eedf710?server=chromium-swarm.appspot.com
> >
> > A m104 mac-rel run:
> > https://ci.chromium.org/swarming/task/5ce441bc4674ee10?server=chromium-swarm.appspot.com
> >
> > A m104 win10 run:
> > https://ci.chromium.org/swarming/task/5ce44226ffe15210?server=chromium-swarm.appspot.com
> >
> > Bug: 1346781
> > Recipe-Nontrivial-Roll: build_limited
> > Change-Id: I21c47d9659152bbdfacd6d0420d58bd9c406c20a
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3813031
> > Reviewed-by: Garrett Beaty <gbeaty@google.com>
> > Commit-Queue: Ben Pastene <bpastene@chromium.org>
>
> Bug: 1346781
> Change-Id: Ib9134de768ae2339afea8948f97ed24e8ac5257e
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3852268
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Auto-Submit: Ben Pastene <bpastene@chromium.org>

Bug: 1346781
Recipe-Nontrivial-Roll: build_limited
Change-Id: I3c80446a640469a53c27158bc668c616e34df43b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3879292
Reviewed-by: Garrett Beaty <gbeaty@google.com>
Commit-Queue: Ben Pastene <bpastene@chromium.org>