Revert of Invoke subprocess.popen() to reload itself instead of os.execv() (patchset #4 id:50001 of https://codereview.chromium.org/2351823007/ )
Reason for revert:
$ make start
sh -c 'ulimit -s 8192; python run_slave.py --no_save -y buildbot.tac'
Syncing projects: 100% (23/23), done.

________ running '/usr/bin/python build/scripts/tools/runit.py python build/scripts/common/cros_chromite.py -v' in '/mnt/data/b'
INFO:root:Updated 0 cache artifact(s).

________ running '/usr/bin/python build/scripts/tools/runit.py python build_internal/scripts/common_internal/cros_chromite_internal.py -v' in '/mnt/data/b'
INFO:root:Updated 0 cache artifact(s).
Traceback (most recent call last):
  File "run_slave.py", line 650, in <module>
    sys.argv.remove(skip_sync_arg)
ValueError: list.remove(x): x not in list
make: *** [start] Error 1

Original issue's description:
> Invoke subprocess.Popen() to reload itself instead of os.execv()
>
> 1) run_slave.py invokes os.execv() to restart itself after gclient-sync
> : https://chromium.googlesource.com/chromium/tools/build.git/+/master/slave/run_slave.py#638
>
> 2) os.execv() on windows does not replace the process image, but rather spawns a new process and terminates itself: i.e., fork() + exit()
>
> * http://bugs.python.org/issue19066
> * From https://msdn.microsoft.com/en-us/library/886kc0as.aspx,
> "... these functions loads and executes a new process, passing an array of pointers to command-line arguments."
>
> 3) As a result, on windows, run_slave.py terminates and restarts itself with a new process id.
>
> 4) Due to #3, service_manager believes the spawned process for buildbot service died, and keep re-spawning processes for buildbot infinitely.
> : https://chromium.googlesource.com/infra/infra.git/+/master/infra/services/service_manager/service_thread.py#131
>
>
> We could have just reloaded all the loaded modules after gclient-sync:
>
> # reload all the loaded modules
> map(reload, sys.modules.values())
>
> However, it may cause unexpected flaky failures in some corner cases.
> : https://docs.python.org/2/library/functions.html#reload
> "Reloading sys, __main__, builtins and other key modules is not recommended. In many cases extension modules are not designed to be initialized more than once, and may fail in arbitrary ways when reloaded."
>
>
> BUG=601499
> R=dsansome@chromium.org, dsansome@google.com, sergiyb@chromium.org, sergiyb@google.com
> CC=vadmish@google.com,dnj@google.com,sergeyberezin@google.com
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/a2f81e8b65ae04ce7f912400a731539a85e6da05

TBR=dsansome@google.com,agable@chromium.org,sergiyb@chromium.org,dsansome@chromium.org,ddoman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=601499

Review-Url: https://codereview.chromium.org/2366873002