chromium: remove no_prune_venv
we don't need to set --no_prune_venv.

with --no_prune_venv, official Mac canary builders fails
like
[47511/48957] ACTION
//chrome:sign_chrome_framework_for_widevine(//build/toolchain/mac:clang_x64)
 FAILED: Google Chrome Framework.sig
 python ../../third_party/widevine/scripts/signature_generator.py --input_file Google\ Chrome\ Framework.framework/Versions/80.0.3955.0/Google\ Chrome\ Framework --output_file Google\ Chrome\ Framework.sig --flags 1
 Traceback (most recent call last):
  File "../../third_party/widevine/scripts/signature_generator.py", line 120, in <module>
   args.passphrase_debug, args.flags))
  File "../../third_party/widevine/scripts/signature_generator.py", line 76, in _GenerateSignatureFile
   import signer
  File "/b/s/w/ir/cache/builder/src/third_party/widevine/scripts/signer.py", line 17, in <module>
   from cryptography import x509
 ImportError: No module named cryptography

Bug: 1020061, 984451
Recipe-Nontrivial-Roll: release_scripts
Recipe-Nontrivial-Roll: build_limited_scripts_slave
Change-Id: I595872334fc583e1517ccdc4cdba7bdc96ec4230
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/1900517
Reviewed-by: John Budorick <jbudorick@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@chromium.org>