Revert of Wait cloudtail termination in goma module (patchset #7 id:120001 of https://codereview.chromium.org/2386073002/ )
Reason for revert:
https://build.chromium.org/p/tryserver.client.pdfium/builders/win_xfa_clang/builds/1134/steps/stop%20cloudtail/logs/stdio

Traceback (most recent call last):
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 111, in <module>
    sys.exit(main())
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 108, in main
    wait_termination(int(f.read()))
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 69, in wait_termination
    os.waitpid(pid, 0)
OSError: [Errno 10] No child processes
step returned non-zero exit code: 1

Need to ignore OSError ECHILD?

Original issue's description:
> Wait cloudtail termination in goma module
>
> This is follow up CL for https://codereview.chromium.org/2375843005/
>
> BUG=
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/5ba4397bb3ab875a37501ec8eb0de33d1b4a1514

TBR=vadimsh@chromium.org,phajdan.jr@chromium.org,ukai@chromium.org,shinyak@chromium.org,yyanagisawa@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2399403005