[update_scripts] Fix Git commands on Windows.
"update_scripts" currently calls "git" without specifying an extension,
which leads Python to call "git.exe". Git invocations go through
"git.bat" at this stage (before CIPD bootstrap), and "git.exe" is not
in PATH, causing this command to fail. It fails with a stack trace, but
to no consqeuence:

Traceback (most recent call last):
  File "E:\b\build\scripts\slave\update_scripts.py", line 146, in update_scripts
    rv, out = get_repo_head(path)
  File "E:\b\build\scripts\slave\update_scripts.py", line 69, in get_repo_head
    return _run_command(cmd, cwd=path, stdout=subprocess.PIPE)
  File "E:\b\build\scripts\slave\update_scripts.py", line 31, in _run_command
    proc = subprocess.Popen(cmd, **kwargs)
  File "E:\b\depot_tools\python276_bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "E:\b\depot_tools\python276_bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

By using "shell=True" on Windows systems, we allow "cmd.exe" to resolve
"git" from PATH and PATHEXT, which should resolve to the system's Git
(likely "git.bat").

BUG=None
TEST=None
R=iannucci@chromium.org

Change-Id: I221a90b32b915cbfebe4dfd76d78bd1363b34ae6
Reviewed-on: https://chromium-review.googlesource.com/569179
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Commit-Queue: Robbie Iannucci <iannucci@chromium.org>