export_tarball: Add new Breakpad test dir, ignore non-existent ones.
https://chromium-review.googlesource.com/c/chromium/src/+/681838, which is
present since M63, moved Breakpad from src/breakpad to
third_party/breakpad/breakpad, which broke the creation of testdata tarball.

From https://ci.chromium.org/buildbot/chromium.infra.cron/publish_tarball/8791:

Traceback (most recent call last):
  File "/b/rr/tmpUmbkYn/rw/recipes/.recipe_deps/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 201, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/b/rr/tmpUmbkYn/rw/recipes/.recipe_deps/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 175, in main
    arcname=os.path.join(output_basename, directory))
  File "/b/rr/tmpUmbkYn/rw/recipes/.recipe_deps/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 118, in add
    tarfile.TarFile.add(self, name, arcname=arcname, recursive=recursive)
  File "/b/cipd_path_tools/lib/python2.7/tarfile.py", line 2009, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/b/cipd_path_tools/lib/python2.7/tarfile.py", line 1881, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/b/rr/tmpUmbkYn/w/src/breakpad/src/processor/testdata'

Add the new location, and just skip test directories that do not exist so
that exporting M62 tarballs continues working.

Change-Id: Id914a8cd32811ce94aee2743f474516153687263
Reviewed-on: https://chromium-review.googlesource.com/743623
Commit-Queue: Raphael Kubo da Costa (rakuco) <raphael.kubo.da.costa@intel.com>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Reviewed-by: Aaron Gable <agable@chromium.org>