Fix compile.py exec failure by 139213002.
del is not EchoDict friendly.  It cause following error:
    sys.exit(real_main())
  File "../../../scripts/slave/compile.py", line 1212, in real_main
    return main(options, args)
  File "../../../scripts/slave/compile.py", line 861, in main_ninja
    env.print_overrides()
  File "../../../scripts/slave/compile.py", line 52, in print_overrides
    fh.write('  %s=%s\n' % (k, self[k]))
KeyError: 'NO_NACL_GOMA'

This change make EchoDict support del.
Use set instead of dict for self.overrides.  self.overrides[key] = True
sounds like we can cancel this with self.overrides[key] = False but
it actually not.  Also, I do not think compile.py is executed by
python version < 2.4.

Review URL: https://codereview.chromium.org/141163005

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@245542 0039d316-1c4b-4281-b951-d872f2087c98