Revert "WebRTC: Add video quality loopback test to android. Take 3"
This reverts commit 4f434debc09adac5440df5ab546dbf06ff135a95.

Reason for revert: 
Breaks the bots. https://build.chromium.org/p/client.webrtc.perf/builders/Android32%20Tests%20%28L%20Nexus4%29/builds/166/steps/video_quality_loopback_test/logs/stdio

INFO:root:Running ['/usr/bin/python', 'out/Release/bin/run_AppRTCMobileTestStubbedVideoIO']
/usr/bin/python: can't open file 'out/Release/bin/run_AppRTCMobileTestStubbedVideoIO': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/b/c/b/Android32_Tests__L_Nexus4_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 132, in <module>
    sys.exit(main())
  File "/b/c/b/Android32_Tests__L_Nexus4_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 82, in main
    _RunCommand([sys.executable, test_script])
  File "/b/c/b/Android32_Tests__L_Nexus4_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 37, in _RunCommand
    subprocess.check_call(argv, cwd=cwd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'out/Release/bin/run_AppRTCMobileTestStubbedVideoIO']' returned non-zero exit status 2

Original change's description:
> WebRTC: Add video quality loopback test to android. Take 3
> 
> BUG=chromium:685222
> 
> Change-Id: Ia3f95d1660557023062c9a3d6d7fd175b6ce1bd5
> Reviewed-on: https://chromium-review.googlesource.com/441346
> Reviewed-by: Henrik Kjellander <kjellander@chromium.org>
> Commit-Queue: Edward Lesmes <ehmaldonado@chromium.org>
> 

TBR=kjellander@chromium.org,ehmaldonado@chromium.org,chromium-reviews@chromium.org,ehmaldonado@webrtc.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:685222

Change-Id: I73edcf005dde946cb5f10aea1199bdcdaa67456f
Reviewed-on: https://chromium-review.googlesource.com/444404
Reviewed-by: Edward Lesmes <ehmaldonado@chromium.org>
Commit-Queue: Edward Lesmes <ehmaldonado@chromium.org>