Reland of WebRTC: Add cleanup_symlinks step on all bots. (patchset #1 id:1 of https://codereview.chromium.org/2492823002/ )
Reason for revert:
Relanding since the failure was caused by a Google storage transient outage rather than because of this change:

subprocess.CalledProcessError: Command '['wget', '--quiet', '-t', '3', '-O', '/b/build/slave/linux64/build/src/chromium/src/build/linux/debian_wheezy_i386-sysroot/debian_wheezy_i386_sysroot.tgz', 'https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/7d200a1ddfeb50dbf9f7e2c1c4ff1080679edf02/debian_wheezy_i386_sysroot.tgz']' returned non-zero exit status 8
Error: Command '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in

https://build.chromium.org/p/client.webrtc/builders/Linux%20%28more%20configs%29/builds/165/steps/gclient%20runhooks/logs/stdio

Original issue's description:
> Revert of WebRTC: Add cleanup_symlinks step on all bots. (patchset #1 id:1 of https://codereview.chromium.org/2484423003/ )
>
> Reason for revert:
> This might be breaking Linux (more configs)
>
> Original issue's description:
> > WebRTC: Add cleanup_symlinks step on all bots.
> >
> > Now that this is finally working as intended in the client.webrtc.fyi
> > waterfall we should be able to turn it on for all bots.
> >
> > BUG=663278
> >
> > Committed: https://chromium.googlesource.com/chromium/tools/build/+/73ebb69974d1d0f2f979da0e6a129100a83d2a78
>
> TBR=kjellander@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=663278
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/fa77e5b771b53a6b007c88c46cb100c56a7395e8

TBR=ehmaldonado@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=663278

Review-Url: https://codereview.chromium.org/2493093003