Revert of Remove all the files in the temp directory on a slave, instead of a whitelist of files. (https://codereview.chromium.org/431863002/)
Reason for revert:
Breaks StartVirtualX() because it relies on a temp file. I'm sure we can fix that and reland, but I'm reverting for now to get the bots green in the meantime.

Traceback (most recent call last):
  File "../../../scripts/slave/runtest.py", line 1904, in <module>
    sys.exit(main())
  File "../../../scripts/slave/runtest.py", line 1875, in main
    result = _MainLinux(options, args, extra_env)
  File "../../../scripts/slave/runtest.py", line 1261, in _MainLinux
    server_dir=special_xvfb_dir)
  File "/b/build/scripts/slave/xvfb.py", line 61, in StartVirtualX
    raise Exception('Display already present.')
Exception: Display already present.

Example:
http://build.chromium.org/p/chromium.perf/builders/Linux%20Perf%20%282%29/builds/2519/steps/page_cycler.intl_ja_zh/logs/stdio

Original issue's description:
> Remove all the files in the temp directory on a slave, instead of a whitelist of files.
> 
> The current whitelist still left > 60K files on some windows trybots, and that led to an increase of 15-20 minutes per try job on the most cluttered bots.
> 
> BUG=399109
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=286846

TBR=maruel@chromium.org,iannucci@chromium.org,jam@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=399109

Review URL: https://codereview.chromium.org/432003006

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@286863 0039d316-1c4b-4281-b951-d872f2087c98