Revert "WebRTC: Add new Android Video Quality test to Android Perf bots."
This reverts commit b373cf63b72495df7a78a4afd2f544612bf4bb8d.

Reason for revert: 

/usr/bin/python /b/c/b/Android32_Tests__K_Nexus5_/src/webrtc/examples/androidtests/video_quality_loopback_test.py out/Release
INFO:root:Running ['gn', 'gen', '/tmp/tmpg8G_2y/LocalBuild']
ERROR Can't find source root.
I could not find a ".gn" file in the current directory or any parent,
and the --root command-line argument was not specified.
Traceback (most recent call last):
  File "/b/c/b/Android32_Tests__K_Nexus5_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 135, in <module>
    sys.exit(main())
  File "/b/c/b/Android32_Tests__K_Nexus5_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 72, in main
    _RunCommand(['gn', 'gen', build_dir_x86])
  File "/b/c/b/Android32_Tests__K_Nexus5_/src/webrtc/examples/androidtests/video_quality_loopback_test.py", line 37, in _RunCommand
    subprocess.check_call(argv, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/tmp/tmpg8G_2y/LocalBuild']' returned non-zero exit status 1


Original change's description:
> WebRTC: Add new Android Video Quality test to Android Perf bots.
> 
> BUG=chromium:685222
> 
> Change-Id: Id9a204c23c36be80ab6c7d00dc7eef0b847b414f
> Reviewed-on: https://chromium-review.googlesource.com/441024
> Reviewed-by: Henrik Kjellander <kjellander@chromium.org>
> Commit-Queue: Edward Lesmes <ehmaldonado@chromium.org>
> 

TBR=kjellander@chromium.org,ehmaldonado@chromium.org,ehmaldonado@webrtc.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:685222

Change-Id: Ife41f9c99a57cacdb06359247fd44c91d539d21c
Reviewed-on: https://chromium-review.googlesource.com/441765
Reviewed-by: Edward Lesmes <ehmaldonado@chromium.org>
Commit-Queue: Edward Lesmes <ehmaldonado@chromium.org>