Try to fix Windows Isolate Tests.
It currently complains about

  WindowsError: [Error 193] %1 is not a valid Win32 application

( http://build.chromium.org/p/chromium.swarm/builders/Windows%20Isolate%20Tests/builds/4644/steps/browser_tests/logs/stdio )

I'm guessing that's because .py files aren't directly executable on Windows.

TBR=maruel@chromium.org

Review URL: https://codereview.chromium.org/26635002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@227635 0039d316-1c4b-4281-b951-d872f2087c98