Revert "Clean up some legacy builders.pyl fields, do more validation."
This reverts commit 0729378e5819c9b7d97f69115ec05605e83d1bfe.

Reason for revert: Might be bricking slaves (cautionary revert).

On "make start":
  ...
  File "/b/build/scripts/common/chromium_utils.py", line 2018, in ParseBuildersFileContents
    raise BuildersFileError(path, errors)
common.chromium_utils.BuildersFileError:   File "/b/build_internal/masters/master.client.server.goma/builders.pyl":
    builder["Goma Server Trusty Presubmit"] did not specify a scheduler

Original change's description:
> Clean up some legacy builders.pyl fields, do more validation.
> 
> This removes the `default_remote_run_properties`,
> `default_remote_run_repository`, `remote_run_sync_revision`, and
> `remote_run_use_gitiles` fields from builders.pyl, and adds
> checks to make sure that a) if a builder specifies use_remote_run
> it also specifies remote_run_repository, and b) every builder
> specifies a recipe and a scheduler (where the scheduler can be
> None but a recipe can't be).
> 
> Bug:
> Change-Id: I444e3da669dc0e10e1574a9852053c25d7cd4350
> Reviewed-on: https://chromium-review.googlesource.com/572151
> Commit-Queue: Dirk Pranke <dpranke@chromium.org>
> Reviewed-by: Daniel Jacques <dnj@chromium.org>

TBR=dpranke@chromium.org,dnj@chromium.org

Change-Id: I76a995617653111ab72765609fe6207f8a891380
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/578793
Reviewed-by: Daniel Jacques <dnj@chromium.org>
Commit-Queue: Daniel Jacques <dnj@chromium.org>