Revert "gatekeeper: remove forgiving_optional from chrome builders."
This reverts commit 94f49d50798cc38aac90fe349978565d0b832273.

Reason for revert:
Causes gatekeeper to fail:
ValueError: You must specify at least one of closing_optional,forgiving_optional or set respect_build_status for builder "*" on master https://build.chromium.org/p/chrome.

https://ci.chromium.org/p/infra/builders/cron/Chromium%20Gatekeeper/b8903139884045751344

Original change's description:
> gatekeeper: remove forgiving_optional from chrome builders.
> 
> Should hopefully stop gatekeeper from closing the tree any time
> a test fails on linux-chromeos-google-rel.
> 
> Bug: 938113, 1001057
> Change-Id: I9542a4df98ac4ff0457607477c91c9d0f90dc9bd
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/1787531
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Commit-Queue: Ben Pastene <bpastene@chromium.org>
> Auto-Submit: John Budorick <jbudorick@chromium.org>

TBR=dpranke@chromium.org,bpastene@chromium.org,jbudorick@chromium.org

Change-Id: I7838dbdaaec205eec40aecf31cf599d3287dc875
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 938113, 1001057
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/1787553
Reviewed-by: Edward Lesmes <ehmaldonado@chromium.org>
Commit-Queue: Edward Lesmes <ehmaldonado@chromium.org>