Openscreen: Add more Code Coverage tooling
This CL adds the following changes to support code coverage:
- Setting of output properties needed by the code coverage module
- Differentiation of per-cl and full-repo coverage for code_coverage
  module'

NOTE: I am currently hitting a permissions issue trying to schedule ci
bot runs on LED. Investigation is ongoing, but because this change wont
affect trybots (validated) it should be good to check in
Error: "googleapi: Error 403: User "user:rwkeane@google.com" is not
allowed to schedule tasks in the pool "luci.flex.ci", see pools.cfg"

Change-Id: I5e08c6c450bca3e6005615b15fb832aff6f78c1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/2220637
Reviewed-by: mark a. foltz <mfoltz@chromium.org>
Commit-Queue: Ryan Keane <rwkeane@google.com>
Auto-Submit: Ryan Keane <rwkeane@google.com>