Revert of Adding gantt chart to Build Status page on Buildbot Masters (patchset #13 id:240001 of https://codereview.chromium.org/2484593002/ )
Reason for revert:
This fails on all masters the moment we sync. Now, master1 was synced after a restart of chromium.fyi and this change became life on all masters of master1. Log says:
	  File "../master.chromium/templates/build.html", line 12, in template
	    {'name': '{{ s.getName()|escapejs }}',
	jinja2.exceptions.TemplateAssertionError: no filter named 'escapejs'

Original issue's description:
> Adding gantt chart to Build Status page on Buildbot Masters
>
> Screenshots:
> Initial page load - https://screenshot.googleplex.com/NJjHFTcXU9T.png
> After button clicked - https://screenshot.googleplex.com/QHn0DLd0Jv9.png
>
> BUG=663245
> TEST=local
>  - ran local buildbot, generated screenshots
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/f128e42562e0a67c111394c5f398ef9b1d93b6bd

TBR=tansell@chromium.org,dsansome@chromium.org,estaab@chromium.org,iannucci@chromium.org,martiniss@chromium.org,sergiyb@chromium.org,philwright@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=663245

Review-Url: https://codereview.chromium.org/2489813002