Revert of Set GOMA_CACHE_DIR to store cache of CRLs. (patchset #1 id:1 of https://codereview.chromium.org/1191203003/)
Reason for revert:
Breaks the compile (http://build.chromium.org/p/chromium.linux/builders/Linux%20Builder%20%28dbg%29%2832%29/builds/39166/steps/compile/logs/stdio)


/tmp/goma.ipc not found
GOMA_CACHE_DIR=/b/build/slave/goma_cache: unknown GOMA_ parameter
compiler proxy failed to run
Traceback (most recent call last):
  File "/b/build/scripts/slave/compile.py", line 1389, in <module>
    sys.exit(real_main())
  File "/b/build/scripts/slave/compile.py", line 1385, in real_main
    return main(options, args)
  File "/b/build/scripts/slave/compile.py", line 933, in main_ninja
    goma_ready = goma_setup(options, env)
  File "/b/build/scripts/slave/compile.py", line 182, in goma_setup
    UploadGomaCompilerProxyInfo()
  File "/b/build/scripts/slave/compile.py", line 257, in UploadGomaCompilerProxyInfo
    log_path = UploadToGomaLogGS(latest_info, os.path.basename(latest_info))
  File "/usr/lib/python2.7/posixpath.py", line 112, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

Original issue's description:
> Set GOMA_CACHE_DIR to store cache of CRLs.
> 
> BUG=492770
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=295763

TBR=iannucci@chromium.org,ukai@chromium.org,shinyak@chromium.org,shinyak@google.com,yyanagisawa@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=492770

Review URL: https://codereview.chromium.org/1192333002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@295764 0039d316-1c4b-4281-b951-d872f2087c98