Revert of WebRTC: Switch client.webrtc Android bots over to recipes (take 2) (https://codereview.chromium.org/240143002/)
Reason for revert:
Build failures due to --revision src@5919 being passed to gclient sync. 
Provision devices step also fails:
OSError: [Errno 2] No such file or directory when executing ['/b/build/slave/Android_Chromium-APK_Tests__KK_Nexus5_/build/src/build/android/provision_devices.py', '-t', 'Release']


Original issue's description:
> WebRTC: Switch client.webrtc Android bots over to recipes (take 2)
> 
> This re-deploys the buildbot config of
> https://codereview.chromium.org/229463005
> (that was reverted in r262948)
> 
> With the fixes in https://codereview.chromium.org/235243003/
> and the mentioned WebRTC fixes in that CL, this switch
> should work.
> 
> BUG=346198
> TEST=None
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=264193

TBR=phoglund@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=346198

Review URL: https://codereview.chromium.org/240363002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@264195 0039d316-1c4b-4281-b951-d872f2087c98