Revert "Reland "Stop using and remove layout_test_wrapper.py.""
This reverts commit f288129199bd2f4dea95a5bbe38220b24d70df2e.

Reason for revert: Broke WebKit Android

https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Android%20%28Nexus4%29

Traceback (most recent call last):
  File "/b/rr/tmpFsr6eK/rw/checkout/scripts/slave/runtest.py", line 1775, in <module>
    sys.exit(main())
  File "/b/rr/tmpFsr6eK/rw/checkout/scripts/slave/runtest.py", line 1744, in main
    result = _MainAndroid(options, args, extra_env)
  File "/b/rr/tmpFsr6eK/rw/checkout/scripts/slave/runtest.py", line 1392, in _MainAndroid
    raise Exception('runtest.py without --run-python-script not supported for '
Exception: runtest.py without --run-python-script not supported for Android
step returned non-zero exit code: 1

Original change's description:
> Reland "Stop using and remove layout_test_wrapper.py."
> 
> Now, run-webkit-tests should be able to start xvfb itself (after http://crbug.com/711515).
> 
> I predict that if this is relanded now, runtest.py should not start xvfb, but run-webkit-tests should start xvfb for itself.
> 
> This is a revert of https://chromium-review.googlesource.com/c/466597/
> 
> BUG=695700
> 
> Change-Id: I34a7a3c6ecbcd93761953ace756de3b9890ada2a
> Reviewed-on: https://chromium-review.googlesource.com/481033
> Commit-Queue: Quinten Yearsley <qyearsley@chromium.org>
> Reviewed-by: Paweł Hajdan Jr. <phajdan.jr@chromium.org>
> 

TBR=mmoss@chromium.org,phajdan.jr@chromium.org,qyearsley@chromium.org,dpranke@chromium.org,tansell@chromium.org,tansell@google.com,chromium-reviews@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=695700

Change-Id: Ia0a3b31117fbc5241d945805f2f3728c17785d96
Reviewed-on: https://chromium-review.googlesource.com/483029
Reviewed-by: Quinten Yearsley <qyearsley@chromium.org>
Commit-Queue: Quinten Yearsley <qyearsley@chromium.org>