Revert "goma_utils.py: use filename to detect timestamp"
This reverts commit 64ce664382fe28331f8941de7748184a8edf77f7.

Reason for revert: 
https://ci.chromium.org/ui/p/chromium/builders/ci/fuchsia-x64-cast/107478/overview
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8856771381340584448/+/steps/postprocess_for_goma/0/steps/upload_log/0/stdout


0 gomacc logs are new
 Traceback (most recent call last):
   File "/b/s/w/ir/kitchen-checkout/build/recipes/upload_goma_logs.py", line 259, in <module>
     sys.exit(main())
   File "/b/s/w/ir/kitchen-checkout/build/recipes/upload_goma_logs.py", line 172, in main
     override_gsutil=override_gsutil
   File "/b/s/w/ir/kitchen-checkout/build/recipes/goma_utils.py", line 247, in UploadGomaCompilerProxyInfo
     gomacc_logs = GetListOfGomaccInfoAfterCompilerProxyStart()
   File "/b/s/w/ir/kitchen-checkout/build/recipes/goma_utils.py", line 124, in GetListOfGomaccInfoAfterCompilerProxyStart
     recent_goamcc_infos.sort()
 NameError: global name 'recent_goamcc_infos' is not defined

Original change's description:
> goma_utils.py: use filename to detect timestamp
>
> GetLogFileTimestamp is too slow so upload_log
> step would time out if too many glog files detected.
>
> glog filename will be
> <cmd>.<host>.<user>.log.<severify>.<yyyy><mm><dd>-<hh><mm><ss>.<xxxxx>
> so use filename to detect timestamp
> rather than reading log contents.
>
> also limit at most 100 log files (first 50 + last 50).
>
> Bug: 1171885
> Change-Id: Ifd8ef38db4f0d9ff58398d5670d52534447056b9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/2658898
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> Reviewed-by: Yoshisato Yanagisawa <yyanagisawa@google.com>
> Reviewed-by: Ye Kuang <yekuang@google.com>
> Auto-Submit: Fumitoshi Ukai <ukai@google.com>

TBR=ukai@google.com,yyanagisawa@google.com,tikuta@chromium.org,jwata@google.com,yekuang@google.com,infra-scoped@luci-project-accounts.iam.gserviceaccount.com

Change-Id: Ib5f6db7e2ef0fa354107d480c3faf53949ed9345
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1171885
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/2658701
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>