Revert of Enable goma on pdfium buildbots by default. (patchset #1 id:1 of https://codereview.chromium.org/2380553002/ )
Reason for revert:
https://uberchromegw.corp.google.com/i/client.pdfium/builders/windows

https://uberchromegw.corp.google.com/i/client.pdfium/builders/windows/builds/1680/steps/start%20cloudtail/logs/stdio

Traceback (most recent call last):
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 63, in <module>
    sys.exit(main())
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 52, in main
    start_cloudtail(args)
  File "E:\b\build\scripts/slave\recipe_modules\goma\resources\cloudtail_utils.py", line 26, in start_cloudtail
    close_fds=True)
  File "E:\b\depot_tools\python276_bin\lib\subprocess.py", line 666, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

Original issue's description:
> Enable goma on pdfium buildbots by default.
>
> This CL is reland of https://codereview.chromium.org/2367263002/
> fix: use close_fds in goma module https://codereview.chromium.org/2374543005/
>
> BUG=643139
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/d1a446fed9dca1ce0cdf0d5abdc2b5e45b4e9976

TBR=phajdan.jr@chromium.org,dpranke@chromium.org,thestig@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=643139

Review-Url: https://codereview.chromium.org/2377193002