Revert of Update export_tarball.py (patchset #1 id:1 of https://codereview.chromium.org/1981553002/ )
Reason for revert:
Failure in the export_tarball step

Example build:
https://build.chromium.org/p/chromium.infra.cron/builders/publish_tarball/builds/3466

Traceback (most recent call last):
  File "/b/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 191, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/b/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 167, in main
    archive.add(options.src_dir, arcname=output_basename)
  File "/b/build/scripts/slave/recipe_modules/chromium/resources/export_tarball.py", line 100, in add
    rel_name = os.path.relpath(name, GetSourceDirectory())
NameError: global name 'GetSourceDirectory' is not defined

Original issue's description:
> Update export_tarball.py
> 
> - Exclude .git directories only. Stop mentioning SVN.
> - Exclude the out directory.
> - Remove obsolete non-essential directories from the list.
> - Move some non-essential directories to the test data list.
> - Add a list of essential files to override the non-essential dir list.
> 
> BUG=611199
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=300596

TBR=phajdan.jr@chromium.org,thestig@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=611199

Review-Url: https://codereview.chromium.org/1984053003

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@300630 0039d316-1c4b-4281-b951-d872f2087c98