Revert of LogDog: Fix butler/annotee package error. (patchset #1 id:1 of https://codereview.chromium.org/2022623002/ )
Reason for revert:
problem

Original issue's description:
> LogDog: Fix butler/annotee package error.
>
> Pass CipdBinary to CIPD installer, not CipdPackage. This fixes a LogDog
> bootstrapping failure:
>
> ERROR:annotated_run:Exception while bootstrapping LogDog.
> Traceback (most recent call last):
>   File "../../../scripts/slave/annotated_run.py", line 263, in _exec_recipe
>     recipe_cmd)
>   File "/b/build/scripts/slave/logdog_bootstrap.py", line 428, in bootstrap
>     for b in (plat.butler, plat.annotee)))
>   File "/b/build/scripts/slave/logdog_bootstrap.py", line 334, in _install_cipd
>     cmd += ['-P', '%s@%s' % (b.package.name, b.package.version)]
> AttributeError: 'CipdPackage' object has no attribute 'package'
>
> TBR=sheyang@chromium.org
> BUG=chromium:550673
> TEST=None
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/0d40fcf2b70f95b3c6bfd3dcf6cef06bed01c4ab

TBR=sheyang@chromium.org,dnj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:550673

Review URL: https://codereview.chromium.org/2011213005 .