Revert "Add runisolatedtest.py script"
This reverts commit 8ab33b7691697cfc6d99a1de3f96f9c04911700c.

Broke WebKit bots:

http://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%2032/builds/5275/steps/webkit_tests/logs/stdio

Traceback (most recent call last):
    File "../../../scripts/slave/runtest.py", line 1129, in <module>
        sys.exit(main())
      File "../../../scripts/slave/runtest.py", line 1106, in main
        result = main_linux(options, args)
      File "../../../scripts/slave/runtest.py", line 834, in main_linux
        extra_env=extra_env)
      File "../../../scripts/slave/runtest.py", line 94, in _RunGTestCommand
        return chromium_utils.RunCommand(command, pipes=pipes, env=env)
      File "/mnt/data/b/build/scripts/common/chromium_utils.py", line 817, in RunCommand
        print '\n' + subprocess.list2cmdline(command) + '\n',
          File "/usr/lib/python2.6/subprocess.py", line 541, in list2cmdline
        needquote = (" " in arg) or ("\t" in arg) or ("|" in arg) or not arg
    TypeError: argument of type 'NoneType' is not iterable

TBR=csharp@chromium.org

BUG=none

Review URL: https://codereview.chromium.org/12668005

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@187818 0039d316-1c4b-4281-b951-d872f2087c98