Revert "api.build.python won't run runit.py with vpython."
This reverts commit a4935e24022a8bba02259dab526e6f2e49bebb53.

Reason for revert:
Traceback (most recent call last):
  File "/b/rr/tmpSYKlzT/rw/checkout/scripts/slave/upload_goma_logs.py", line 16, in <module>
    from slave import goma_bq_utils
ImportError: No module named slave
To lots of builders, sigh.

Original change's description:
> api.build.python won't run runit.py with vpython.
> 
> tl;dr if venv=True,
> * before this cl:
> runit.py: vpython
> upload_goma_logs.py: vpython
> * after this cl:
> runit.py: platform python
> upload_goma_logs.py: vpython
> 
> Running vpython inside vpython could be a cause of crbug.com/821689.
> Let me make runit.py not invoked by vpython but make runit.py to
> invoke others with vpython if venv=True.
> 
> Current behavior is like:
> If venv=True, runit.py is invoked with vpython without
> --with-third-party-libs flag, and runit.py invokes child process
> with vpython if the flag is not given.
> 
> I do not think runit.py use libraries that need to be executed
> with vpython, and make runit.py executed with platform python instead
> of vpython to avoid running vpython inside vpython.
> 
> Bug: 822103
> Change-Id: Ic1bb526be6ef7aa338de0bf35d818734640355b8
> Recipe-Nontrivial-Roll: infra
> Recipe-Nontrivial-Roll: build_limited_scripts_slave
> Recipe-Nontrivial-Roll: release_scripts
> Reviewed-on: https://chromium-review.googlesource.com/963953
> Commit-Queue: Yoshisato Yanagisawa <yyanagisawa@chromium.org>
> Reviewed-by: Sergiy Byelozyorov <sergiyb@chromium.org>

TBR=iannucci@chromium.org,yyanagisawa@chromium.org,machenbach@chromium.org,sergiyb@chromium.org

Change-Id: I763f82e7c4a871b57be9152970867d3ca3ff63cc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 822103
Reviewed-on: https://chromium-review.googlesource.com/963882
Reviewed-by: Yoshisato Yanagisawa <yyanagisawa@chromium.org>
Commit-Queue: Yoshisato Yanagisawa <yyanagisawa@chromium.org>