Revert of WebRTC: Enable bot_update for standalone recipe. (patchset #5 id:820001 of https://codereview.chromium.org/472963003/)
Reason for revert:
Turns out our Mac trybots are using a too old version of Git (git/1.7.4.1) the patch step fails like this:

Applying the patch.
Failed to apply patch for codereview.settings:
While running git apply --index -3 -p1 --verbose;
  error: unknown switch `3'

Original issue's description:
> WebRTC: Enable bot_update for standalone recipe.
> 
> Depends on https://codereview.chromium.org/627493002/ being
> landed first.
> 
> BUG=webrtc:3534, 419516
> TEST=Passing build with https://codereview.chromium.org/627493002/ applied:
> scripts/tools/run_recipe.py webrtc/standalone buildername="Linux64 Debug" mastername=client.webrtc slavename=x revision='"7417"' use_mirror=True
> Also tried a trybot:
> scripts/tools/run_recipe.py webrtc/standalone buildername="linux" mastername=tryserver.webrtc slavename=x revision='"7417"' patchset=1 issue=12659005 rietveld=https://webrtc-codereview.appspot.com use_mirror=True root=src
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=292403

TBR=hinoka@chromium.org,hinoka@google.com
NOTREECHECKS=true
NOTRY=true
BUG=webrtc:3534, 419516

Review URL: https://codereview.chromium.org/644813006

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@292404 0039d316-1c4b-4281-b951-d872f2087c98