Revert of remove chromium_trybot_legacy recipe and associated code and bots. (patchset #1 id:1 of https://codereview.chromium.org/1397963002/ )
Reason for revert:
This patch broke downstream simulation tests.  See https://chromium.googlesource.com/external/github.com/luci/recipes-py/+/master/doc/cross_repo.md#Local-development for how to test locally.

Example failure:

======================================================================
ERROR: chrome.full_chrome_continuous_precise32_stable (/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/recipes/chrome.expected/full_chrome_continuous_precise32_stable.json)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/third_party/expect_tests/pipeline.py", line 163, in generate_tests_results
    for subtest, subresult in test.process(process_test):
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/third_party/expect_tests/type_definitions.py", line 232, in process
    yield self, func(self.bind(context=None))
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/third_party/expect_tests/pipeline.py", line 140, in process_test
    subresult = subtest.run()
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/third_party/expect_tests/type_definitions.py", line 221, in run
    return self.func_call(context=context)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/third_party/expect_tests/type_definitions.py", line 146, in __call__
    return f.func(*f.args, **f.kwargs)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/simulation_test.py", line 27, in RunRecipe
    test_data.properties, stream, _UNIVERSE, test_data)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/run.py", line 494, in run_steps
    return engine.run(recipe_module.RunSteps, api, prop_defs)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/run.py", line 895, in run
    steps_function, api._engine.properties, prop_defs, api=api)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/loader.py", line 442, in invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/recipes/chrome.py", line 48, in RunSteps
    test_spec)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/recipe_api.py", line 218, in _inner
    return func(*a, **kw)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/build/scripts/slave/recipe_modules/chromium_tests/api.py", line 352, in compile
    master_dict, test_spec)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/recipe_engine/recipe_engine/recipe_api.py", line 218, in _inner
    return func(*a, **kw)
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/build/scripts/slave/recipe_modules/chromium_tests/api.py", line 314, in get_compile_targets_and_tests
    compile_targets.update(t.compile_targets(self.m))
  File "/usr/local/google/home/luqui/b/build/slave/fake_slave/build/recipe_roller/build_limited_scripts_slave/.recipe_deps/build/scripts/slave/recipe_modules/chromium_tests/steps.py", line 141, in compile_targets
    for s in self._all_compile_targets[self._script]]
KeyError: 'nacl_integration.py'


Original issue's description:
> remove chromium_trybot_legacy recipe and associated code and bots.
> 
> This CL removes the chromium_trybot_legacy recipe and the following
> bots that were using it:
> 
> on tryserver.chromium.linux:
>   - linux_arm
>   - linux_chromium_trusty32_dbg
>   - linux_chromium_trusty32_rel
>   - linux_chromium_trusty_dbg
>   - linux_chromium_trusty_rel
> on tryserver.chromium.win:
>   - win_chromium_x64_dbg
>   - win8_chromium_dbg
>   - win8_chromium_rel
> 
> R=phajdan.jr@chromium.org
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=297075

TBR=phajdan.jr@chromium.org,dpranke@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1396313004

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@297096 0039d316-1c4b-4281-b951-d872f2087c98