Revert of ensure_goma for goma canary (patchset #1 id:1 of https://codereview.chromium.org/1814713002/ )
Reason for revert:
Seems to have broken most bots, e.g.

https://build.chromium.org/p/tryserver.chromium.linux/builders/chromeos_amd64-generic_chromium_compile_only_ng/builds/108797/steps/ensure_goma/logs/stdio

with

Traceback (most recent call last):
  File "/b/build/scripts/slave/recipe_modules/goma/resources/ensure_goma.py", line 70, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/b/build/scripts/slave/recipe_modules/goma/resources/ensure_goma.py", line 51, in main
    if arg.canary:
NameError: global name 'arg' is not defined

Original issue's description:
> ensure_goma for goma canary
> 
> for bot configured as goma_canary, it will use head of goma repo,
> instead of pinned revision configured in ensure_goma.py
> 
> BUG=595234
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=299374

TBR=phajdan.jr@chromium.org,iannucci@chromium.org,ukai@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=595234

Review URL: https://codereview.chromium.org/1811953003

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@299375 0039d316-1c4b-4281-b951-d872f2087c98