Reland "Reland "Reland "Reland "update swarming client for python3""""
This reverts commit 3976cd4c5b49c7d39c501c519973007cdb9a741a.

Reason for revert:

https://crrev.com/i/4974665 stopped using swarming.py in iOS
swarming_cron builder.

Original change's description:
> Revert "Reland "Reland "Reland "update swarming client for python3""""
>
> This reverts commit 2f3373fde0367b1e37fd06d33a920ce822be38d9.
>
> Reason for revert: This breaks iOS swarming_cron
>
> Original change's description:
> > Reland "Reland "Reland "update swarming client for python3"""
> >
> > This reverts commit 601bbe59415352c18d70cf7ed16393d977cad9b3.
> >
> > Reason for revert:
> >
> > This includes fix for ModuleNotFoundError in
> > https://chromium.googlesource.com/infra/luci/client-py.git/+/6b5e452e39fc4c629c40726b0421d495e40b3620
> >
> >
> > Original change's description:
> > > Revert "Reland "Reland "update swarming client for python3"""
> > >
> > > This reverts commit ebdf8901cb52c591af2b6437a658311f291cfd05.
> > >
> > > Reason for revert: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-upload-perfetto/140058/overview
> > > ModuleNotFoundError: No module named 'DEPS'
> > > crbug.com/1357015
> > >
> > > Original change's description:
> > > > Reland "Reland "update swarming client for python3""
> > > >
> > > > This reverts commit 0ffac362f17a8aeaf35f0a260fe0f0444d9fc718.
> > > >
> > > > Reason for revert:
> > > >
> > > > swarming.py has embedded vpython spec in
> > > > https://crrev.com/c/3855656
> > > >
> > > > Original change's description:
> > > > > Revert "Reland "update swarming client for python3""
> > > > >
> > > > > This reverts commit c42fc41b7c82a05e001f587d97c47c5d6ceaeffb.
> > > > >
> > > > > Reason for revert: Breaks bling/swarming_cron recipe, see https://ci.chromium.org/ui/p/chrome/builders/ci/swarming-cron/99237/overview
> > > > >
> > > > >
> > > > > Original change's description:
> > > > > > Reland "update swarming client for python3"
> > > > > >
> > > > > > This reverts commit 6881b561348a7d5b391a05f78d216232b74c4687.
> > > > > >
> > > > > > Reason for revert:
> > > > > >
> > > > > > Update objc wheel version in .vpython3 to use
> > > > > > * https://chrome-infra-packages.appspot.com/p/infra/python/wheels/pyobjc/mac-arm64_cp38_cp38/+/version:7.3.chromium.1
> > > > > > * https://chrome-infra-packages.appspot.com/p/infra/python/wheels/pyobjc/mac-amd64_cp38_cp38/+/version:7.3.chromium.1
> > > > > >
> > > > > > Original change's description:
> > > > > > > Revert "update swarming client for python3"
> > > > > > >
> > > > > > > This reverts commit d29f606548a7ac7b3a1d3e16020561e93a0d3926.
> > > > > > >
> > > > > > > Reason for revert:
> > > > > > > https://ci.chromium.org/ui/p/webrtc/builders/ci/MacARM64%20M1%20Release/3506/overview
> > > > > > >
> > > > > > > Original change's description:
> > > > > > > > update swarming client for python3
> > > > > > > >
> > > > > > > > This uses the latest swarming client with vpython3 as a preparation for
> > > > > > > > the reland of https://crrev.com/c/3808653.
> > > > > > > >
> > > > > > > > Tested with
> > > > > > > > $ led get-build 8806781422210063921 | led edit-recipe-bundle | \
> > > > > > > >   led launch
> > > > > > > > https://ci.chromium.org/swarming/task/5c80ceb9f90f9310?server=chromium-swarm.appspot.com
> > > > > > > >
> > > > > > > >
> > > > > > > > $ led get-build 8806778439451515841 | led edit-recipe-bundle | \
> > > > > > > >   led launch
> > > > > > > > https://ci.chromium.org/swarming/task/5c80ceeef6d6d210?server=chromium-swarm.appspot.com
> > > > > > > >
> > > > > > > >
> > > > > > > > Recipe-Nontrivial-Roll: build_limited
> > > > > > > > Bug: 1327534
> > > > > > > > Change-Id: Ia4f5ab07abb9bf92a0a8089865fd0db002843241
> > > > > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3810033
> > > > > > > > Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> > > > > > > > Reviewed-by: Ben Pastene <bpastene@chromium.org>
> > > > > > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > > > > >
> > > > > > > Bug: 1327534
> > > > > > > Change-Id: I8ffe6d210623cd5173f4b89501a591ebfaa6c529
> > > > > > > No-Presubmit: true
> > > > > > > No-Tree-Checks: true
> > > > > > > No-Try: true
> > > > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3838529
> > > > > > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > > > > > Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> > > > > > > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > > > >
> > > > > > Recipe-Nontrivial-Roll: build_limited
> > > > > > Bug: 1327534
> > > > > > Change-Id: I67b4ae5333fa69cd899332f4c386426ee5c1d929
> > > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3838531
> > > > > > Reviewed-by: Junji Watanabe <jwata@google.com>
> > > > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > > >
> > > > > Bug: 1327534
> > > > > Recipe-Nontrivial-Roll: build_limited
> > > > > Change-Id: I3d8c61a98d87e5712fe9986cc740c447229e08ba
> > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3853021
> > > > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > > > Auto-Submit: Garrett Beaty <gbeaty@google.com>
> > > > > Reviewed-by: Junji Watanabe <jwata@google.com>
> > > > > Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
> > > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > >
> > > > Recipe-Nontrivial-Roll: build_limited
> > > > Bug: 1327534
> > > > Change-Id: Icedd20f3404c8b3e844f6c12f706c724eb05e28d
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3858862
> > > > Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > > Reviewed-by: Junji Watanabe <jwata@google.com>
> > >
> > > Bug: 1327534, 1357015
> > > Change-Id: I48508ff0858d88be430d3328bfb8de6e5cb57a5a
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3859308
> > > Auto-Submit: Ben Pastene <bpastene@chromium.org>
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> >
> > Recipe-Nontrivial-Roll: build_limited
> > Bug: 1327534, 1357015
> > Change-Id: I3c7b1501ba446471c42c55ec7553b12d2fd2e28e
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3864736
> > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> > Reviewed-by: Garrett Beaty <gbeaty@google.com>
>
> Recipe-Nontrivial-Roll: build_limited
> Bug: 1327534, 1357015
> Change-Id: If2794ba3e95e2fa30cabc829bd77bd3bdbd16d4c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3884018
> Reviewed-by: Garrett Beaty <gbeaty@google.com>
> Commit-Queue: Garrett Beaty <gbeaty@google.com>
> Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>

Bug: 1327534, 1357015
Recipe-Nontrivial-Roll: build_limited
Change-Id: I89d518c5483e5495be83f6ee4a9cddcb02b2628c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3885817
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Takuto Ikuta <tikuta@chromium.org>