Fix uncaught exception for newly added blink scripts
This was introduced in https://codereview.chromium.org/1294763002

Traceback (most recent call last):
  File "/b/build/third_party/recipe_engine/main.py", line 869, in run
    retcode = steps_function(api)
  File "/b/build/scripts/slave/recipes/chromium_trybot.py", line 618, in RunSteps
    return _RunStepsInternal(api)
  File "/b/build/scripts/slave/recipes/chromium_trybot.py", line 597, in _RunStepsInternal
    compile_targets.extend(test.compile_targets(api))
  File "/b/build/scripts/slave/recipe_modules/chromium_tests/steps.py", line 136, in compile_targets
    for s in self._all_compile_targets[self._script]]
KeyError: 'webkit_lint.py'

BUG=431479

Review URL: https://codereview.chromium.org/1293753002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@296310 0039d316-1c4b-4281-b951-d872f2087c98