Revert of ARB: Use commit message generated by roll-dep (patchset #3 id:40001 of https://codereview.chromium.org/577463002/)
Reason for revert:
(Apparently?) causing presubmit errors on all build CQs

** Presubmit ERRORS **
scripts/tools/blink_roller/auto_roll_test.py (0.62s) failed
Traceback (most recent call last):
  File "scripts/tools/blink_roller/auto_roll_test.py", line 10, in <module>
    import auto_roll
  File
"/b/infra_internal/commit_queue/workdir/tools/build/scripts/tools/blink_roller/auto_roll.py",
line 132, in <module>
    class AutoRoller(object):
  File
"/b/infra_internal/commit_queue/workdir/tools/build/scripts/tools/blink_roller/auto_roll.py",
line 144, in AutoRoller
    'revlog_url': '.+',
TypeError: not enough arguments for format string

Original issue's description:
> ARB: Use commit message generated by roll-dep
> 
> BUG=408700
> R=szager@chromium.org
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=291982

TBR=eseidel@chromium.org,szager@chromium.org,borenet@google.com
NOTREECHECKS=true
NOTRY=true
BUG=408700

Review URL: https://codereview.chromium.org/575803004

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@291984 0039d316-1c4b-4281-b951-d872f2087c98