Revert of Use gsutil.py wrapper for recipe gsutil usage. (patchset #3 id:40001 of https://codereview.chromium.org/818313002/)
Reason for revert:
As far as I can tell, this has broken all of Skia's Windows bots due to a problem with path formatting:

http://chromegw.corp.google.com/i/client.skia/builders/Perf-Win7-ShuttleA-HD2000-x86-Release-ANGLE/builds/544/steps/gsutil%20download%20skps/logs/stdio

InvalidUriError: "c:\0\build\slave\Perf-Win7-ShuttleA-HD2000-x86-Release-ANGLE\build\playback" contains ":" instead of "://".
WARNING:root:Command c:\0\depot_tools\python276_bin\python.exe -u c:\0\depot_tools\gsutil.py --force-version 3.4 cp -R gs://chromium-skia-gm/playback_191/skps c:\0\build\slave\Perf-Win7-ShuttleA-HD2000-x86-Release-ANGLE\build\playback failed with retcode 1, try 1.1.

I will un-revert if it's still broken.

Original issue's description:
> Use gsutil.py wrapper for recipe gsutil usage.
> 
> BUG=434422
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=293511

TBR=pgervais@chromium.org,hinoka@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=434422

Review URL: https://codereview.chromium.org/828183003

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@293517 0039d316-1c4b-4281-b951-d872f2087c98