runtest.py: Fix the bot json arg for graphing type tests.
crrev.com/c/3100413 tried to add the bot json arg for graphing type
tests. However that didn't quite work since they're now failing with:
AttributeError: 'GraphingLogProcessor' object has no attribute 'PrepareJSONFile'

It turns out that the type of 'log_processor' differs between gtests
and 'graphing' style tests, and only the former implements the
PrepareJSONFile method.

However, PrepareJSONFile() is a pretty dumb method. It's only value is
in creating a temporary test_launcher_summary_output if one wasn't
passed explicitly on the command-line. So we can bypass
PrepareJSONFile() and just add test_launcher_summary_output directly
to the command line of the test if we know it's not empty.

Bug: webrtc:13073
Change-Id: Ica83a9a33e3e1b6d88fc0aed0ad55573a4e00cca
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/3104105
Reviewed-by: Dirk Pranke <dpranke@google.com>
Reviewed-by: Mirko Bonadei <mbonadei@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>