Revert "Fix manifest_to_hashes to work properly."
This reverts commit 600c7c79487e71cee246a2e921d1341204027939.

The following error was observed when restarting the FYI waterfall:

  File "/home/chrome-bot/buildbot/build/masters/master.chromium.fyi/master.cfg", line 23, in <module>
    from master.factory import chromium_factory
  File "/home/chrome-bot/buildbot/build/scripts/master/factory/chromium_factory.py", line 12, in <module>
    from master.factory import chromium_commands
  File "/home/chrome-bot/buildbot/build/scripts/master/factory/chromium_commands.py", line 22, in <module>
    from master.factory import swarm_commands
exceptions.SyntaxError: invalid syntax (swarm_commands.py, line 107)

BUG=
TBR=maruel@chromium.org

Review URL: https://codereview.chromium.org/11082003

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@160575 0039d316-1c4b-4281-b951-d872f2087c98