mac: use mac_xcode_version = xcode_12_beta to request that version
https://ci.chromium.org/p/chromium/builders/ci/mac-arm64/345:

ValueError: unexpected AST node: <_ast.BinOp object at 0x110000e50> BinOp(left=Num(n=12), op=Sub(), right=Name(id='beta', ctx=Load())) (inside '12-beta')

Python’s ast treats a hyphen as a token that’s the subtraction operator,
and anything that begins with a digit as a token that’s a number. So
12-beta isn’t a good name, and neither is 12_beta or xcode-12-beta. But
xcode_12_beta should be just fine.

Depends on https://chromium-review.googlesource.com/c/2265141/

Bug: chromium:1098454,chromium:1099242
Change-Id: I5d847dad82573b28e2dc1b76afe84be447474301
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/2265761
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Auto-Submit: Mark Mentovai <mark@chromium.org>