Fix encoding issue for authorize_adb_devices.py under python3
The script throws the following exception under python3:
  TypeError: a bytes-like object is required, not 'str'

Bug: 1413191, 1411973
Change-Id: Ie0ddb5dd634040cf5acd9edc27bb3883862e7e3b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/4226491
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Haiyang Pan <hypan@google.com>
Auto-Submit: Haiyang Pan <hypan@google.com>