Revert 240859 "Add uploading of LAST_CHANGE file for zip_build.py."
Broke chromium.linux:

  File "../../../scripts/slave/zip_build.py", line 196, in WriteRevisionFile
      tmp_revision_file.write('%d' % build_revision)
      TypeError: %d format: a number is required, not str

> Add uploading of LAST_CHANGE file for zip_build.py.
> 
> A LAST_CHANGE file will make it possible to use the
> build/scripts/master/url_poller.py to poll for new builds
> that has been created in other waterfalls than the builder.
> 
> I also refactored slave_utils a bit to extract the
> revision handling logic into its own function to make
> GetZipFileNames a bit more readable.
> More refactoring is needed in this area, but I didn't
> want this CL to grow into something enormous.
> 
> TEST=locally running the step on a local slave checkout:
> Plain Chromium build:
> scripts/slave/runbuild.py --master-dir masters/master.chromium.webrtc --builder="Linux Builder" --override-brdostep --stepfilter=package_build --logfile=-
> A build that uses the --revision-dir flag:
> scripts/slave/runbuild.py --master-dir masters/master.client.webrtc --builder="Android Chromium-APK Builder" --override-brdostep --stepfilter=slave_steps --logfile=-
> 
> Review URL: https://codereview.chromium.org/95403002

TBR=kjellander@chromium.org

Review URL: https://codereview.chromium.org/116213002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@240861 0039d316-1c4b-4281-b951-d872f2087c98