Revert of [recipe_modules/test_results] Refactor the logic of generating full json results files (patchset #1 id:1 of https://codereview.chromium.org/2460953002/ )
Reason for revert:
breaks result generation:

Traceback (most recent call last):
  File "/b/rr/tmppE_6sh/rw/checkout/infra/.recipe_deps/build/scripts/slave/recipe_modules/test_results/resources/upload_test_results.py", line 156, in <module>
    sys.exit(main())
  File "/b/rr/tmppE_6sh/rw/checkout/infra/.recipe_deps/build/scripts/slave/recipe_modules/test_results/resources/upload_test_results.py", line 138, in main
    master_name=options.master_name)
TypeError: generate_json_results_file() got an unexpected keyword argument 'builder_number'

e.g. from https://build.chromium.org/p/chromium.android/builders/Lollipop%20Low-end%20Tester/builds/4229/steps/Upload%20to%20test-results%20%5Bandroid_webview_test_apk%5D/logs/stdio

Original issue's description:
> [recipe_modules/test_results] Refactor the logic of
> generating full json results files to a single method
>
> The motivation is we will add logic to not generate full
> json results files if the json already has full JSON
> results format.
>
> This CL is a pure refactoring CL, there is no intended
> behavior change.
>
> BUG=649762
>
> Committed: https://chromium.googlesource.com/chromium/tools/build/+/0f5673778f3f8aa418d5ba97153ba7499ab4ad42

TBR=kbr@chromium.org,estaab@chromium.org,phajdan.jr@chromium.org,nednguyen@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=649762

Review-Url: https://codereview.chromium.org/2464843003